### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by liefhunter** [Qliangw/notion_sync_data#1]
你好，在运行python run.py -h的时候，发现错误提示。具体信息如下
File "run.py", line 45
    log_detail.warn(f'【Tip】您输入的-m参数为< {media} >,请输入< python run.py -h >查看正确指令')
                                                                                                                 ^
SyntaxError: invalid syntax
不知道是什么原因造成的，我是在MacBook上运行的，感谢您的分享

**Comment by Qliangw** [comment]
根据提示是run.py 第 45 行附近存在语法错误，方便看一下您电脑的python版本么（我windows系统使用的3.10.2），版本不同的话，我去试试其他版本复现一下该错误

**Comment by liefhunter** [comment]
> 根据提示是 run.py 第 45 行附近存在语法错误，方便看一下您电脑的 python 版本么（我 windows 系统使用的 3.10.2），版本不同的话，我去试试其他版本复现一下该错误

谢谢你的答复，我发现使用 python3 run.py 以后就没有问题了，可能在mac上python run.py 使用的是老版本所以造成了这个问题。非常感谢！

**Comment by liefhunter** [comment]
> > 根据提示是 run.py 第 45 行附近存在语法错误，方便看一下您电脑的 python 版本么（我 windows 系统使用的 3.10.2），版本不同的话，我去试试其他版本复现一下该错误
> 
> 谢谢你的答复，我发现使用 python3 run.py 以后就没有问题了，可能在 mac 上 python run.py 使用的是老版本所以造成了这个问题。非常感谢！

不好意思，我发现初始化的时候，好像还是在报错，python的版本是3.10.1
❯ python3 run.py -f init
初始化数据库
Traceback (most recent call last):
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/tool/notion/databases.py", line 236, in create_database
    log_detail.info(f"【RNU】创建{media_type}数据库--初始化参数")
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/utils/log_detail.py", line 74, in info
    return Logger.get_instance().logger.info(text)
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/utils/log_detail.py", line 63, in get_instance
    Logger.__instance = Logger()
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/utils/log_detail.py", line 25, in __init__
    if user_config['app']:
KeyError: 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/haosun/GitHub/notion_sync_data/run.py", line 49, in <module>
    init_database()
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/app/sync.py", line 124, in init_database
    create_database(token=token, page_id=page_id, media_type=media_type[0])
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/tool/notion/databases.py", line 255, in create_database
    log_detail.error(f"【RUN】创建数据库错误{err}")
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/utils/log_detail.py", line 78, in error
    return Logger.get_instance().logger.error(text)
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/utils/log_detail.py", line 63, in get_instance
    Logger.__instance = Logger()
  File "/Users/haosun/GitHub/notion_sync_data/sync_data/utils/log_detail.py", line 25, in __init__
    if user_config['app']:
KeyError: 'app'

**Comment by Qliangw** [comment]
拉取一下最新的库 配置文件中有新增内容
