### ISSUE TITLE
初始化数据库报错

### ISSUE THREAD

**Issue by BinReco** [Qliangw/notion_sync_data#2]
Mac电脑 Python3.10
binner@binner notion_sync_data % python3 run.py -f init
初始化数据库
Traceback (most recent call last):
  File "/Users/binner/notion_sync_data/run.py", line 49, in <module>
    init_database()
  File "/Users/binner/notion_sync_data/sync_data/app/sync.py", line 103, in init_database
    create_database(token=token, page_id=page_id)
  File "/Users/binner/notion_sync_data/sync_data/tool/notion/databases.py", line 113, in create_database
    db_data = base.NotionBaseInfo(token=token)
  File "/Users/binner/notion_sync_data/sync_data/tool/notion/base.py", line 15, in __init__
    log_detail.debug("【RUN】notion参数初始化...")
  File "/Users/binner/notion_sync_data/sync_data/utils/log_detail.py", line 70, in debug
    return Logger.get_instance().logger.debug(text)
  File "/Users/binner/notion_sync_data/sync_data/utils/log_detail.py", line 63, in get_instance
    Logger.__instance = Logger()
  File "/Users/binner/notion_sync_data/sync_data/utils/log_detail.py", line 25, in __init__
    if user_config['app']:
KeyError: 'app'

**Comment by Qliangw** [comment]
## 多谢您的测试！

本地更改了配置文件，没有在`/doc/[config.yaml.simple](https://github.com/Qliangw/notion_sync_data/blob/main/doc/config.yaml.simple)` 更新，下载重新下载这个配置文件即可

**Comment by BinReco** [comment]
更新本地文件后，成功了，但是更新了几条后，出现这个，这块我就不太明白了
【RUN】随机休眠时间5-10s，本次休眠：10s
【RUN】请求url，获取返回值
【RUN】解析书籍信息
【RUN】解析失败：list index out of range
Traceback (most recent call last):
  File "/Users/binner/notion_sync_data/run.py", line 43, in <module>
    start_sync(media_type=media, media_status=status)
  File "/Users/binner/notion_sync_data/sync_data/app/sync.py", line 93, in start_sync
    html_dict[MediaInfo.URL.value] = url
TypeError: list indices must be integers or slices, not str

**Comment by Qliangw** [comment]
解析失败：list index out of range 报错说的是没有获取到链接 确认一下豆瓣的user_id是否填写，然后想看、正在看、看过的哪里有没有标记信息。

- 想看： https://book.douban.com/people/你的user_id/wish 
- 在看： https://book.douban.com/people/你的user_id/do
- 看过： https://book.douban.com/people/你的user_id/collect

如果没有的可能会报错 下次更新我修复一下这个问题

**Comment by BinReco** [comment]
https://book.douban.com/people/kobegalbraith/wish

**Comment by BinReco** [comment]
user_id是对的

**Comment by Qliangw** [comment]
![image](https://user-images.githubusercontent.com/22791711/156971062-fb3851b1-a56a-4a8a-8fe7-bcee7c4d3133.png)

我在linux平台测试是正常的（非开发环境，我换了另个一机器）

**Comment by Qliangw** [comment]
> 更新本地文件后，成功了，但是更新了几条后，出现这个，这块我就不太明白了 【RUN】随机休眠时间5-10s，本次休眠：10s 【RUN】请求url，获取返回值 【RUN】解析书籍信息 【RUN】解析失败：list index out of range Traceback (most recent call last): File "/Users/binner/notion_sync_data/run.py", line 43, in start_sync(media_type=media, media_status=status) File "/Users/binner/notion_sync_data/sync_data/app/sync.py", line 93, in start_sync html_dict[MediaInfo.URL.value] = url TypeError: list indices must be integers or slices, not str

已解决 拉取最新库即可
