### ISSUE TITLE
初始化时候显示错误

### ISSUE THREAD

**Issue by lvjiaoyang3232138** [Qliangw/notion_sync_data#37]
Traceback (most recent call last):
  File "C:\Users\32321\Desktop\notion_sync_data-main\run.py", line 9, in <module>
    from sync_data.app.sync import start_sync, init_database, merge_old_cfg
  File "C:\Users\32321\Desktop\notion_sync_data-main\sync_data\app\sync.py", line 9, in <module>
    from sync_data.tool.douban import base
  File "C:\Users\32321\Desktop\notion_sync_data-main\sync_data\tool\douban\base.py", line 6, in <module>
    import requests.utils
ModuleNotFoundError: No module named 'requests'
请问这个怎么处理呀，还是说我的依赖环境没有安装好

**Comment by Qliangw** [comment]
不用下载源码了，需要安装依赖，在这里我有打包好的，直接运行即可： https://github.com/Qliangw/notion_sync_data/releases 这里下载运行试试看
