### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by Nuofan-SUSTech** [Qliangw/notion_sync_data#8]
运行命令 `python run.py -m book -s all` 时，软件开始将豆瓣上标记的书籍倒入到 Notion 对应的页面上。但运行一段时间之后，会出现以下这种报错：

```
Traceback (most recent call last):
  File "run.py", line 52, in <module>
    start_sync(media_type=media, media_status=i)
  File "/home/nuofan/notion_sync_data/sync_data/app/sync.py", line 277, in start_sync
    err_url_list = get_monitoring_and_update(instance=douban_instance,
  File "/home/nuofan/notion_sync_data/sync_data/app/sync.py", line 98, in get_monitoring_and_update
    html_dict[MediaInfo.URL.value] = url
TypeError: list indices must be integers or slices, not str
```
出错时的书籍页面是: [I Was Britpopped](https://book.douban.com/subject/27595438/)
其他信息：
- Ubuntu 18.04.6 LTS
- Python 3.8.5

**Comment by Qliangw** [comment]
感谢反馈

下个版本处理一下这个问题
